#!/bin/bash

# Copyright (C) 2023 M.Angel Juan
#
# This file is part of LLXAMP.
#
# LLXAMP is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# LLXAMP is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with LLXAMP.  If not, see <http://www.gnu.org/licenses/>.


SOURCESMD5FILE=sources.md5
SOURCE_DIR=/tmp/llxamp-sources
INSTALL_PACK_DIR=/tmp/llxamp-install-pack
[ -d "$SOURCE_DIR" ] && SOURCE_FILES=$(ls $SOURCE_DIR/*.tar.gz|xargs -n1 basename)
DECOMPRESSED_DIR=/tmp/llxamp-sources-decompressed
BUILDDIR=/LLXXAMPP
TAG=$BUILDDIR/123456789123456789123456789123456789123456789
DEFAULT_PORT=8080
DEFAULT_SSL_PORT=8443
PACKNAME=install-pack.tgz