#!/bin/bash

# Copyright (C) 2023 M.Angel Juan
#
# This file is part of LLXAMP.
#
# LLXAMP is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# LLXAMP is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with LLXAMP.  If not, see <http://www.gnu.org/licenses/>.


INSTALL_PACK_DIR=/tmp/llxamp-install-pack
DECOMPRESSED_PACK_DIR=/usr/lib/llxamp/pack
BUILDDIR=/LLXXAMPP
TAG=$BUILDDIR/123456789123456789123456789123456789123456789
DEFAULT_PORT=8080
DEFAULT_SSL_PORT=8443
PACKNAME=$(PACKNAME=$(grep -v '#' /usr/lib/llxamp/files | grep -iv 'md5'))
EXT=$(echo $PACKNAME|rev|cut -d. -f1|rev)
if [ "x$ext" = "xzst" ]; then
    COMMAND_TEST="tar --zstd -tf"
    COMMAND_DECOMPRESS="tar --zstd -xf"
    NEED="build-tag httpd php mariadb httpd/htdocs/phpMyAdmin"
else
    COMMAND_TEST="tar -ztf"
    COMMAND_DECOMPRESS="tar xfz"
    NEED="./build-tag ./httpd ./php ./mysql ./httpd/htdocs/phpMyAdmin"
fi