#!/bin/bash

# Copyright (C) 2023 M.Angel Juan
#
# This file is part of LLXAMP.
#
# LLXAMP is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# LLXAMP is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with LLXAMP.  If not, see <http://www.gnu.org/licenses/>.

mountpoint=$HOME/llxamp
lower=/usr/lib/llxamp/pack

if [ -z "$(findmnt -l -o TARGET | grep -o $mountpoint)" ]; then
    if [ -d "$lower" ]; then
        mkdir -p $HOME/.llxamp/{work,upper}
        fuse-overlayfs -olowerdir=$lower,upperdir=$HOME/.llxamp/upper,workdir=$HOME/.llxamp/work,squash_to_uid=$(id -u),squash_to_gid=$(id -g) "$mountpoint" > /dev/null 2>&1
    fi
fi