#!/usr/bin/env python3

from ctypes import Array
import sys
import signal
from gettext import gettext as _
from PySide2 import QtWidgets, QtGui, QtCore

app = None
exitting = False

def exit_control_c(sig, frame):
    global app,exitting
    exitting = True
    print(_("Ending QApplication"))
    sys.exit(0)

signal.signal(signal.SIGINT, signal.SIG_DFL)
signal.signal(signal.SIGINT, exit_control_c)

class MainApp(QtWidgets.QMainWindow):
    def __init__(self, *args, **kwargs):
        super().__init__()
        
        self.setWindowTitle('LLXAMP')
        
        self.setMinimumSize(QtCore.QSize(800,600))
        
        self.setCentralWidget(QtWidgets.QWidget(parent=self))
        self.centralWidget().setSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        
        self.create_menu_bar()
        self.create_layout()
        self.create_buttons()
        self.create_text()
        self.p = None
        # a=self.findChildren(QtWidgets.QMenu,QtCore.QRegularExpression('menu_F'))
        # b=[obj.objectName() for obj in a]
        pass
    
    def create_layout(self):
        l = QtWidgets.QVBoxLayout()
        self.centralWidget().setObjectName('main_layout')
        self.centralWidget().setLayout(l)
        pass
        
    def create_menu_bar(self):
        items = [
            ['File', ['Action1',['SubFile', 'Action2'], 'Action3'] ],
            ['File2', ['jeje', 'Ohhh'] ],
            'juju'
        ]
        for item in items:
            if isinstance(item,list):
                self.menuBar().addMenu(self.create_menu(items=item, parent=self.menuBar()))
            if isinstance(item,str):
                self.menuBar().addAction(self.create_menu(items=item, parent=self.menuBar()))
                
    def create_menu(self, items=[], parent=None):
        if isinstance(items,list):
            newmenu = QtWidgets.QMenu(items[0].capitalize(),parent=parent)
            newmenu.setObjectName('menu_'+items[0])
            for subitem in items[1:]:
                if isinstance(subitem,list):
                    newmenu.addMenu(self.create_menu(items=subitem, parent=newmenu))
                if isinstance(subitem,str):
                    newmenu.addAction(self.create_menu(items=subitem, parent=newmenu))
            return newmenu
        if isinstance(items,str):
            action = QtWidgets.QAction(items.capitalize(),parent=parent)
            action.setData(items)
            action.setObjectName('action_'+items)
            action.setStatusTip(items)
            #action.setIcon(QtWidgets.QIcon())
            #action.setShortCuts(QtCore.QKeySequence())
            action.triggered.connect(self.action_triggered)
            return action
        
    def action_triggered(self):
        action_sender = self.sender()
        text = action_sender.text()
        name = action_sender.objectName()
        try:
            data = action_sender.data()
        except:
            data = None
        
        if data:
            print(f'text={text} data={data} objectName={name}')
        else:
            print(f'text={text} objectName={name}')
        if name == 'button_Exec':
            self.execute_script('llxamp-status')       

    def create_buttons(self):
        txt = "Exec"
        btn = QtWidgets.QPushButton(txt.capitalize(),parent=self.centralWidget())
        btn.setObjectName('button_'+txt)
        btn.setStatusTip(txt)
        btn.pressed.connect(self.action_triggered)
        self.centralWidget().layout().addWidget(btn)
        pass
    
    def find(self,name=''):
        return self.findChildren(QtWidgets.QWidget,QtCore.QRegularExpression(name))
    
    def create_text(self):
        text = QtWidgets.QPlainTextEdit()
        text.setReadOnly(True)
        text.setObjectName('textarea')
        self.centralWidget().layout().addWidget(text)

    def msg(self,txt):
        self.find('textarea')[0].appendPlainText(txt)

    def finish_script(self,process):
        self.msg(f'finished {process.objectName()}')
        self.p = []
    
    def output(self):
        data = bytes(self.p[0].readAllStandardOutput()).decode('utf8').replace('\n','')
        self.msg(data)
    
    def execute_script(self, scriptname):
        if self.p:
            print(f'Running')
        else:
            p = QtCore.QProcess()
            p.setObjectName(scriptname)
            p.finished.connect(lambda: self.finish_script(p))
            p.started.connect(lambda: self.msg(f'started {scriptname}'))
            p.readyReadStandardOutput.connect(self.output)
            self.p = [p]
            p.start(scriptname,[])
        
def main():
    global app, exitting
    
    app = QtWidgets.QApplication(sys.argv)
    window = MainApp()
    window.show()
    exitLoopTimer = QtCore.QTimer()
    exitLoopTimer.timeout.connect(lambda: None)
    exitLoopTimer.start(500)
    sys.exit(app.exec_())

if __name__ == '__main__':
    main()

