#!/bin/bash
set -e
source $1

echo Decompressing archive files

mkdir -p $DECOMPRESSED_DIR
for archive in $SOURCE_FILES; do 
    tar xfz $SOURCE_DIR/$archive -C $DECOMPRESSED_DIR
    linkname=$(echo $archive|sed -nr 's|([a-zA-Z-]+)-.*|\1|p')
    dirname=$(basename $archive .tar.gz)
    ln -s $dirname $DECOMPRESSED_DIR/$linkname
done