#!/bin/bash
set -e
source $1

BUILDDIR=${BUILDDIR:=/LLXXAMP}
OWNER=$(whoami)

echo "Creating build dir '$BUILDDIR' as '$OWNER' (needs sudo)"

sudo mkdir -p $BUILDDIR
sudo chown $OWNER.$OWNER $BUILDDIR
