#!/bin/bash
set -e
source $1

BUILDDIR=${BUILDDIR:=/LLXXAMP}
TAG=${TAG:=$BUILDDIR/123456789123456789123456789123456789123456789}

if [ -e "$DECOMPRESSED_DIR/mariadb/bin/mariadb" ];then
    suffix=mariadb
else
    suffix=mysql
fi
PREFIX=$TAG/$suffix

echo Copying MariaDB files

cp -LR $DECOMPRESSED_DIR/mariadb $PREFIX
