#!/bin/bash
set -e
source ENVIRON

BUILDDIR=${BUILDDIR:=/LLXXAMP}
TAG=${TAG:=$BUILDDIR/123456789123456789123456789123456789123456789}
PACKNAME=${PACKNAME:=pack.tgz}

echo;echo Compressing base install pack;echo;

tar cfz $PACKNAME -C $TAG .

echo;echo Finished;