#!/bin/bash
set -e
source $1

BUILDDIR=${BUILDDIR:=/LLXXAMP}
TAG=${TAG:=$BUILDDIR/123456789123456789123456789123456789123456789}
PACKNAME=${PACKNAME:=pack.tgz}

echo Compressing base install pack

tar cfz $PACKNAME -C $TAG .

echo Finished;