#!/bin/bash
set -e
here=$(realpath .)
output=
for param in "$@"; do
    case "$param" in
        -o*)
            shift
            output=$1
        ;;
        -h*)
            show_help
            exit 0
        ;;
    esac
done

basepath=@@LLXAMP_BASEPATH@@
dirs="httpd/conf httpd/htdocs php/lib/php.ini*"
filename=llxamp-backup

tmp=$(mktemp -d)

cd $tmp

export $(llxamp-status -m)
if [ "x$MYSQL_RUNNING" == "x1" ];then
    llxamp-stop-mysql
    sleep 1
    llxamp-kill-mysql
fi

@@LLXAMP_BASEPATH@@/mysql/bin/mysqld --defaults-file=@@LLXAMP_BASEPATH@@/mysql/conf/my.cnf --skip-grant-tables > /dev/null 2>&1 &
while ! @@LLXAMP_BASEPATH@@/mysql/bin/mysql --defaults-file=@@LLXAMP_BASEPATH@@/mysql/conf/my.cnf --user=root -e 'status' >/dev/null 2>&1; do
    sleep 1;
done;

llxamp-mysqldump --all-databases --add-drop-database --add-drop-table --add-locks --all-tablespaces --comments --complete-insert --dump-date --extended-insert --flush-logs --flush-privileges --routines --triggers --user root > backup-mysql.sql

kill $(cat /home/lliurex/llxamp/mysql/temp/mysql.pid)

if [ "x$MYSQL_RUNNING" == "x1" ];then
    llxamp-start-mysql
fi

cd $basepath

tar -c -f $tmp/$filename.tar -C $basepath $dirs
tar --append -f $tmp/$filename.tar -C $tmp backup-mysql.sql

cd $tmp

gzip -9 $tmp/$filename.tar

if [ -n "$output" ]; then
    cd $here
    d=$(dirname "$output")
    f=$(basename "$output")
    mkdir -p "$d"
    mv $tmp/$filename.tar.gz "$d"/"$f"
    echo "Backup saved in '$d/$f'"
else
    echo "Backup saved in '$tmp/$filename.tar.gz'"
fi
