#!/bin/bash

# Copyright (C) 2023 M.Angel Juan
#
# This file is part of LLXAMP.
#
# LLXAMP is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# LLXAMP is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with LLXAMP.  If not, see <http://www.gnu.org/licenses/>.

if [ -d "@@LLXAMP_BASEPATH@@/mariadb" ]; then
    mysqld_safe=mariadbd-safe
    suffix=mariadb
else
    mysqld_safe=mysqld_safe
    suffix=mysql
fi
@@LLXAMP_BASEPATH@@/$suffix/bin/$mysqld_safe --defaults-file=@@LLXAMP_BASEPATH@@/$suffix/conf/my.cnf > /dev/null 2>&1 &