#!/bin/bash
# Apache
if [ -z "$(ss -Htpnle |grep "uid:$(id -u)"|grep httpd)" ]; then
    echo "Apache: Not running"
else
    ports=$(ss -Htpnle |grep "uid:$(id -u)"|grep httpd|awk '{split($4,port,":"); print port[2];}'|xargs|tr ' ' ',' )
    procs=$(ss -Htpnle |grep "uid:$(id -u)"|grep httpd|awk '{print $6}'|egrep -o 'pid=[0-9]+'|cut -d'=' -f2|xargs|tr ' ' ',' )
    echo "Apache: Running Ports: $ports Procs: $procs"
fi

# Mysql
mysql_running=$()
if [ -z "$(ss -Htpnle |grep "uid:$(id -u)"|grep mysqld)" ]; then
    echo "MySQL: Not running"
else
    ports=$(ss -Htpnle |grep "uid:$(id -u)"|grep mysqld|awk '{split($4,port,":"); print port[2];}'|xargs|tr ' ' ',' )
    procs=$(ss -Htpnle |grep "uid:$(id -u)"|grep mysqld|awk '{print $6}'|egrep -o 'pid=[0-9]+'|cut -d'=' -f2|xargs|tr ' ' ',' )
    echo "MySQL: Running Ports: $ports Procs: $procs"
fi