#!/bin/bash

SOURCE_DIR=/tmp/llxamp-sources
INSTALL_PACK_DIR=/tmp/llxamp-install-pack
SOURCE_FILES=$(grep -v '#' /usr/lib/llxamp/sources/files | grep -vi 'md5')
DECOMPRESSED_DIR=/tmp/llxamp-sources-decompressed
BUILDDIR=/LLXXAMPP
TAG=$BUILDDIR/123456789123456789123456789123456789123456789
DEFAULT_PORT=8080
DEFAULT_SSL_PORT=8443
PACKNAME=install-pack-2.tar.zst