#!/bin/bash
set -e
script_dir=$( cd -- "$( dirname -- $(realpath -e "${BASH_SOURCE[0]}") )" &> /dev/null && pwd )
script_name=$(basename "${BASH_SOURCE[0]}")
path=$(dirname $(realpath -e "$script_dir/$script_name"))

run-parts --exit-on-error "$path"/llxamp-build-parts -a "$path"/environ
